### ISSUE TITLE
[ADD] 미들웨어 추가

### ISSUE THREAD

**Issue by thguss** [Team-Smeme/Smeme-server#46]
## What is this issue? 🚀
소셜 로그인 기능 구현 전 단계의 API에 미들웨어 추가가 필요합니다.

## Progress 🏃‍♀️
- [ ] 일기 작성
- [ ] 게시판 일기 상세 조회

**Comment by unanchoi** [comment]
구현은 진행하고, API 개발이 마무리되는 시점에 router에 연결하겠습니다!
