### ISSUE TITLE
[FEAT] 서버 통신 테스트 API 구현 (클라 요청)

### ISSUE THREAD

**Issue by thguss** [Team-Smeme/Smeme-server#69]
## What is this issue? 🚀
서버 통신 API 개발

## Progress 🏃‍♀️
- [x] 200 반환

**Comment by unanchoi** [comment]
저희 originURL에 get 요청 하는 api 하나 있는 걸로 진행해도 괜찮을 것 같습니다!
<img width="538" alt="image" src="https://user-images.githubusercontent.com/81692211/211133232-d2de353c-1f7b-46bd-a5f7-d6dd50789ae4.png">
